run:
  timeout: 5m
  skip-dirs:
    - docs
  modules-download-mode: readonly
  allow-parallel-runners: true
  go: "1.20"

output:
  format: colored-line-number

linters:
  enable-all: true
  disable:
    - deadcode
    - dupl
    - exhaustive
    - exhaustivestruct
    - exhaustruct
    - funlen
    - golint
    - gomnd
    - ifshort
    - interfacer
    - maligned
    - nlreturn
    - nosnakecase
    - revive
    - scopelint
    - structcheck
    - structcheck
    - testpackage
    - varcheck
    - varnamelen
    - wsl
