run:
  timeout: 5m
  skip-dirs:
    - docs
  modules-download-mode: readonly
  allow-parallel-runners: true
  go: "1.20"

output:
  format: colored-line-number

linters:
  enable-all: true
  disable:
    - testpackage
    - funlen
    - dupl
    - gomnd
    - wsl
    - nlreturn
    - nosnakecase
    - interfacer
    - ifshort
    - varcheck
    - exhaustivestruct
    - scopelint
    - structcheck
    - maligned
    - deadcode
    - golint
    - structcheck
