// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Identifier is an autogenerated mock type for the Identifier type
type Identifier struct {
	mock.Mock
}

type Identifier_Expecter struct {
	mock *mock.Mock
}

func (_m *Identifier) EXPECT() *Identifier_Expecter {
	return &Identifier_Expecter{mock: &_m.Mock}
}

// Identify provides a mock function with given fields:
func (_m *Identifier) Identify() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Identifier_Identify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Identify'
type Identifier_Identify_Call struct {
	*mock.Call
}

// Identify is a helper method to define mock.On call
func (_e *Identifier_Expecter) Identify() *Identifier_Identify_Call {
	return &Identifier_Identify_Call{Call: _e.mock.On("Identify")}
}

func (_c *Identifier_Identify_Call) Run(run func()) *Identifier_Identify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Identifier_Identify_Call) Return(_a0 string) *Identifier_Identify_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Identifier_Identify_Call) RunAndReturn(run func() string) *Identifier_Identify_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewIdentifier interface {
	mock.TestingT
	Cleanup(func())
}

// NewIdentifier creates a new instance of Identifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIdentifier(t mockConstructorTestingTNewIdentifier) *Identifier {
	mock := &Identifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
