name: CI

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

env:
  GO: 1.20.x

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ${{env.GO}}
          cache: true
      - uses: actions/checkout@v3
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52.2
          only-new-issues: true
  
  race-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{env.GO}}
      - run: go test -v --race --count 1 ./...

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{env.GO}}
      - run: go test -v -coverprofile=coverage.txt ./...
      - name: Upload Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.txt
          flags: unittests
          env_vars: GO
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
